### ISSUE TITLE
Custom search pattern not working

### ISSUE THREAD

**Issue by Krabator** [Vysci/LFG-Bulletin-Board#33] opened 2021-06-11 16:48 UTC
I am using the addon on an English client and the custom search patterns are not working.
exemple : in france we use GT2 for "Grotte du temps 2", it's Black Morass in English... i added "gt2" as a custom search pattern for Black Morass... and it does not works.

**Comment by Vysci** [comment] 2021-06-11 17:57
Closing as this is a duplicate of #26

**Closed by Vysci** 2021-06-11 17:57 UTC
Labels: duplicate
