### ISSUE TITLE
Message: Interface/AddOns/LFGBulletinBoard/RequestList.lua:440: attempt to perform arithmetic on field 'last' (a nil value)

### ISSUE THREAD

**Issue by johanpettersson1** [Vysci/LFG-Bulletin-Board#294] opened 2024-07-20 17:44 UTC
Message: Interface/AddOns/LFGBulletinBoard/RequestList.lua:440: attempt to perform arithmetic on field 'last' (a nil value)
Time: Sat Jul 20 19:44:41 2024
Count: 6321
Stack: Interface/AddOns/LFGBulletinBoard/RequestList.lua:440: attempt to perform arithmetic on field 'last' (a nil value)
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:440: in function `Clear'
[string "@Interface/AddOns/LFGBulletinBoard/RequestList.lua"]:478: in function `UpdateList'
[string "@Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua"]:900: in function `Entry'
[string "@Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua"]:125: in function <Interface/AddOns/LFGBulletinBoard/LibGPIToolBox.lua:123>

Locals: newRequest = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
}
(for control) = 5
i = 5
req = <table> {
 dungeon = "DFC"
 IsPastPlayer = false
 guid = "Player-5220-0269456E"
 start = 1721497359.616000
 class = "ROGUE"
 IsFriend = false
 IsGuildMember = false
}
(*temporary) = nil
(*temporary) = 10800
(*temporary) = "attempt to perform arithmetic on field 'last' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:133
 CreateTagList = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:392
 GetDungeonNames = <function> defined @Interface/AddOns/LFGBulletinBoard/Dungeons.lua:12
 ClearNeeded = true
 InitGroupList = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupList.Lua:177
 TBCMAXDUNGEON = 32
 LfgRequestHideTooltip = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:727
 tagList = <table> {
 }
 GetSortedDungeonKeys = <function> defined @Interface/AddOns/LFGBulletinBoard/dungeons/classic.lua:273
 suffixTags = <table> {
 }
 LevelRange = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:129
 ParseMessage = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:774
 LFG_Successfulljoined = true
 ClearTimer = 1721497341.680000
 UpdateLfgToolNoSearch = <function> defined @Interface/AddOns/LFGBulletinBoard/LfgToolList.lua:229
 NotifySound = 1210
 JoinLFG = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:195
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:941
 ClickFrame = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:981
 CreateChatFrame = <function> defined @Interface/AddOns/LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:328
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:871
 WOTLKDUNGEONSTART = 33
 dungeonSecondTags = <table> {
 }
 rawClassicDungeonInfo = <table> {
 }
 Version = "3.33"
 TAGBAD = "---"
 GetCustomFilterKeys = <function> defined @Interface/AddOns/LFGBulletinBoard/CustomCategories.lua:148
 GetDungeons = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:584
 GetDungeonSort = <function> defined @Interface/AddOns/LFGBulletinBoard/Dungeons.lua:729
 TBCDUNGEONSTART = 33
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @Interface/AddOns/LFGBulletinBoard/Localization.lua:825
 Popup_Minimap = <function> defined @Interface/AddOns/LFGBulletinBoard/GroupBulletinBoard.lua:476
 ClickDungeon = <function> defined @Interface/AddOns/LFGBulletinBoard/RequestList.lua:988
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 RequestShowTooltip = <function> defined @Interface/AddOns/LFGB

![image](https://github.com/user-attachments/assets/4f9ca36a-4364-4a00-a745-3c286c7049d8)

**Comment by juemrami** [comment] 2024-07-20 18:38
According to the error log you're still on `3.33`, can you try out `3.35-beta` and lmk if you still have errors.

https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board/files/5547426

**Comment by juemrami** [comment] 2024-07-20 18:45
Duplicate of #281

**Comment by juemrami** [comment] 2024-07-22 16:40
closing with `v3.35`

**Closed by juemrami** 2024-07-22 16:40 UTC
Labels: bug, duplicate
