### ISSUE TITLE
custom words for the dungeons (german)

### ISSUE THREAD

**Issue by d4kir92** [Vysci/LFG-Bulletin-Board#24] opened 2021-06-10 08:37 UTC
i added for manatomb the words:
mana managruft

but it still dont get the messages
• lfg (managruft) dd
• lfg dd Managruft!
• lfg mana dd

do you know why?

**Comment by d4kir92** [comment] 2021-06-10 08:47
does your addon lowercase the "custom words"?
and does it remove -> ( ) ! ? ,

**Comment by Vysci** [comment] 2021-06-11 16:27
Closing as a duplicate of issue #26 

German should have been fixed in the latest version 2.50

**Closed by Vysci** 2021-06-11 16:27 UTC
Labels: duplicate
