### ISSUE TITLE
Suggestion: Add option to stop scanning channels in raid/dungeon/instance

### ISSUE THREAD

**Issue by MattZeeX** [Vysci/LFG-Bulletin-Board#170] opened 2022-11-12 07:42 UTC
**Is your feature request related to a problem? Please describe.**
People have alleged that the bulletin board is contributing to lower FPS in raids, whilst I don't know how true this is, it would be nice to be able to turn off what likely may be the "culprit" which would be the scanning of the chat channels and storing the data for x seconds. 

I have my addon storing LFG message for 5 minutes, which is much longer than the default of 2 (I think) minutes. I find this works well for me when looking for a group, but I can imagine that it's a large amount of unnecessary data stored once I actually find a group.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/49168219/201463211-220eddc9-bf8b-4c68-8438-44d0c2adf1de.png)
There is already this drop down to enable/disable chat notifications from the addon when you are in certain areas, I think it would be nice if this were expanded to the addon as a whole, so a dropdown just like this but for enabling/disabling the bulletin board functionality of the addon.

I honestly don't know if the addon causes FPS drops, but I think this would be a nice feature to have implemented, and would help to dissuade people speaking negatively of the addon.

**Comment by juemrami** [comment] 2024-12-03 01:34
closing as a duplicate of #97

Some additional context, these performance issues were addressed in #144 by putting a 0.5s throttle on the updating of the bulletin board.

**Closed by juemrami** 2024-12-03 01:34 UTC
Labels: enhancement
