### ISSUE TITLE
Custom words do not work

### ISSUE THREAD

**Issue by MatthewBerkvens** [Vysci/LFG-Bulletin-Board#35] opened 2021-06-11 18:52 UTC
added AC to auchenai crypts:
https://i.imgur.com/TOlyHW4.png

does not show up under auchenai crypts but miscellaneous instead
https://i.imgur.com/roOsQGP.png
https://i.imgur.com/roOsQGP.png

**Comment by Vysci** [comment] 2021-06-11 19:43
closing as it's a duplicate of #26

**Closed by Vysci** 2021-06-11 19:43 UTC
Labels: duplicate
