### ISSUE TITLE
chat positioning

### ISSUE THREAD

**Issue by swaagbagtag** [Vysci/LFG-Bulletin-Board#247] opened 2024-06-11 14:24 UTC
**Describe the bug**
so usually it will change LFG channel from what i have as /4 to /1 and general from /1 to /2 and trade from /2 to /3 or sometimes just wipe all channels completely

**To Reproduce**
No idea, log in and it is changed

**Expected behavior**
Channels to remain the same

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 all versions

**Comment by juemrami** [comment] 2024-06-12 00:29
Ive had this happen to me as well, but a while back i re-organized my channels in the wow chat settings.

![relevant settings image](https://imgur.com/do9Tn9D) 

And since then ive been unable to get the addon to reproduce this behavior.

From having looked at the code base the only thing that i think could cause this is when a new character is made and the code runs before they join any channels ever. But Ive not been able to reproduce with a fresh character either.

**Comment by juemrami** [comment] 2024-06-12 00:45
I tested again on fresh characaters. I got it to place "LookingForGroup" on `/1` only sometimes.

**Comment by Vysci** [comment] 2024-06-12 01:46
The blizzard function for joining chat channels can be called before the chat channels or joined channels are available. This behavior additionally causes a raise condition with other addons that have you join channels. In the past I have tried to wait before all the chat channels are available before attempting to join but that still left the race condition against other addons to still happen. Didn’t spend more time to investigateOn Jun 11, 2024, at 5:45 PM, Julio Ramirez ***@***.***> wrote:﻿
I tested again on fresh characaters. I got it to place "LookingForGroup" on /1 only sometimes.

**Comment by juemrami** [comment] 2024-06-12 02:17
Its fine if other addon's dont bother waiting and mess up the users channel order, but i think its that we should at least wait.

The fix i drafter will join LFG as soon as *any* other channel is joined, including anything added by another addon.
If that happens, we can consider the users channel order to already be "corrupted" and they should report to whatever other addon theyre using that is joining channels before the officials channels have been joined.

**Comment by Vysci** [comment] 2024-06-12 03:04
While technically you are right, if it results in the issue happening 10x more frequently than it becomes a question of which addon do you like better.

**Comment by juemrami** [comment] 2024-06-12 03:47
Yea, i will change the code specifically check for either general or defense channels before attempting to join. 
There is an API function i found when working on cata that has the pre-translated names for these channels so there shouldnt be any localization issues 

![](https://i.imgur.com/DMMT7Am.png)
![](https://i.imgur.com/ACn6Ksk.png)

**Comment by juemrami** [comment] 2024-06-18 23:02
Closing this with `v3.31`

If youre still having this issue after the update, do the following:

1. Go to the channel order settings (pictured in the original reply)
2. Leave "LookingForGroup"
3. Rejoin by clicking its button in the "Available Channels" section of the same settings.
4. Drag the LFG channel to where you want it to permanently be.

Remember, **this is character specific**.

**Closed by juemrami** 2024-06-18 23:02 UTC
Labels: bug
